apiVersion: v2
name: hello-world
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: postgresql
    version: 11.6.0
    condition: global.postgresql.enabled
    repository: "https://charts.bitnami.com/bitnami"
